# DataSource Config
spring:
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    # p6spy SQL执行效率配置
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3307/mybatisplus
    username: root
    password: 123456

# 配置日志
mybatis-plus:
  configuration:
    # 控制台输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除，不需要注册
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)